name: "CRUK Pattern Library"
version: 1.1.0

markdown: kramdown
highlighter: rouge

kramdown:
  auto_ids: true

permalink: pretty
source: docs
baseurl: "/cruk-pattern-library"

sass:
  sass_dir: ../
  style: compressed

timezone: Europe/London

github:
  repo: https://github.com/CRUKorg/cruk-pattern-library

host: 0.0.0.0
